name: ini
version: 1.1.0
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://gitlab.com/matthewfranglen/dart-ini
description: Read and write .ini files
dev_dependencies:
  test: any
  stream_channel: any
environment:
  sdk: ">=2.0.0 <3.0.0"
