name: ini
version: 2.1.0-beta
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://gitlab.com/matthewfranglen/dart-ini
description: Read and write .ini files
dev_dependencies:
  test: any
  stream_channel: any
environment:
  sdk: '>=2.12.0-0 <3.0.0'
